#!/bin/bash
# wget -O - https://raw.githubusercontent.com/miitchpls/hass-glutz-eaccess/main/install | bash -
set -e

declare path
declare -a paths=(
    "$PWD"
    "$PWD/config"
    "/config"
    "$HOME/.homeassistant"
    "/usr/share/hassio/homeassistant"
)

for p in "${paths[@]}"; do
    if [ -n "$path" ]; then
        break
    fi

    if [ -f "$p/.HA_VERSION" ]; then
        path="$p"
    fi
done

if [ -n "$path" ]; then
    cd "$path"
    if [ ! -d "$path/custom_components" ]; then
        mkdir "$path/custom_components"
    fi
    cd "$path/custom_components"
    echo "Downloading glutz_eaccess..."
    wget -q "https://github.com/miitchpls/hass-glutz-eaccess/releases/latest/download/glutz_eaccess.zip"
    if [ -d "$path/custom_components/glutz_eaccess" ]; then
        rm -R "$path/custom_components/glutz_eaccess"
    fi
    mkdir "$path/custom_components/glutz_eaccess"
    unzip "$path/custom_components/glutz_eaccess.zip" -d "$path/custom_components/glutz_eaccess" >/dev/null 2>&1
    rm "$path/custom_components/glutz_eaccess.zip"
    echo "Installation complete"
    echo "You need to restart Home Assistant before using the integration."
else
    echo "Could not find the directory for Home Assistant"
    echo "Manually change the directory to the root of your Home Assistant configuration with the user that is running Home Assistant and run the script again."
    exit 1
fi